USE acore_world;
START TRANSACTION;
DELETE FROM playercreateinfo WHERE race IN (55,54,58,59,61,60,62,63,66,67,68,74,75,78,98,106,138,33,45,59);
DELETE FROM playercreateinfo_item WHERE race IN (55,54,58,59,61,60,62,63,66,67,68,74,75,78,98,106,138,33,45,59);
DELETE FROM playercreateinfo_action WHERE race IN (55,54,58,59,61,60,62,63,66,67,68,74,75,78,98,106,138,33,45,59);
DELETE FROM player_race_stats WHERE Race IN (55,54,58,59,61,60,62,63,66,67,68,74,75,78,98,106,138,33,45,59);
DELETE FROM ascension_custom_class_race WHERE race IN (55,54,58,59,61,60,62,63,66,67,68,74,75,78,98,106,138,33,45,59);
INSERT INTO playercreateinfo SELECT 55,class,map,zone,position_x,position_y,position_z,orientation FROM playercreateinfo WHERE race=2;
INSERT INTO playercreateinfo_item SELECT 55,class,itemid,amount,Note FROM playercreateinfo_item WHERE race=2;
INSERT INTO playercreateinfo_action SELECT 55,class,button,action,type FROM playercreateinfo_action WHERE race=2;
INSERT INTO player_race_stats SELECT 55,Strength,Agility,Stamina,Intellect,Spirit FROM player_race_stats WHERE Race=2;
INSERT INTO ascension_custom_class_race SELECT DISTINCT class,55 FROM ascension_custom_class_race;
INSERT INTO playercreateinfo SELECT 54,class,map,zone,position_x,position_y,position_z,orientation FROM playercreateinfo WHERE race=1;
INSERT INTO playercreateinfo_item SELECT 54,class,itemid,amount,Note FROM playercreateinfo_item WHERE race=1;
INSERT INTO playercreateinfo_action SELECT 54,class,button,action,type FROM playercreateinfo_action WHERE race=1;
INSERT INTO player_race_stats SELECT 54,Strength,Agility,Stamina,Intellect,Spirit FROM player_race_stats WHERE Race=10;
INSERT INTO ascension_custom_class_race SELECT DISTINCT class,54 FROM ascension_custom_class_race;
INSERT INTO playercreateinfo SELECT 58,class,map,zone,position_x,position_y,position_z,orientation FROM playercreateinfo WHERE race=2;
INSERT INTO playercreateinfo_item SELECT 58,class,itemid,amount,Note FROM playercreateinfo_item WHERE race=2;
INSERT INTO playercreateinfo_action SELECT 58,class,button,action,type FROM playercreateinfo_action WHERE race=2;
INSERT INTO player_race_stats SELECT 58,Strength,Agility,Stamina,Intellect,Spirit FROM player_race_stats WHERE Race=10;
INSERT INTO ascension_custom_class_race SELECT DISTINCT class,58 FROM ascension_custom_class_race;
INSERT INTO playercreateinfo SELECT 59,class,map,zone,position_x,position_y,position_z,orientation FROM playercreateinfo WHERE race=1;
INSERT INTO playercreateinfo_item SELECT 59,class,itemid,amount,Note FROM playercreateinfo_item WHERE race=1;
INSERT INTO playercreateinfo_action SELECT 59,class,button,action,type FROM playercreateinfo_action WHERE race=1;
INSERT INTO player_race_stats SELECT 59,Strength,Agility,Stamina,Intellect,Spirit FROM player_race_stats WHERE Race=10;
INSERT INTO ascension_custom_class_race SELECT DISTINCT class,59 FROM ascension_custom_class_race;
INSERT INTO playercreateinfo SELECT 61,class,map,zone,position_x,position_y,position_z,orientation FROM playercreateinfo WHERE race=1;
INSERT INTO playercreateinfo_item SELECT 61,class,itemid,amount,Note FROM playercreateinfo_item WHERE race=1;
INSERT INTO playercreateinfo_action SELECT 61,class,button,action,type FROM playercreateinfo_action WHERE race=1;
INSERT INTO player_race_stats SELECT 61,Strength,Agility,Stamina,Intellect,Spirit FROM player_race_stats WHERE Race=4;
INSERT INTO ascension_custom_class_race SELECT DISTINCT class,61 FROM ascension_custom_class_race;
INSERT INTO playercreateinfo SELECT 60,class,map,zone,position_x,position_y,position_z,orientation FROM playercreateinfo WHERE race=2;
INSERT INTO playercreateinfo_item SELECT 60,class,itemid,amount,Note FROM playercreateinfo_item WHERE race=2;
INSERT INTO playercreateinfo_action SELECT 60,class,button,action,type FROM playercreateinfo_action WHERE race=2;
INSERT INTO player_race_stats SELECT 60,Strength,Agility,Stamina,Intellect,Spirit FROM player_race_stats WHERE Race=10;
INSERT INTO ascension_custom_class_race SELECT DISTINCT class,60 FROM ascension_custom_class_race;
INSERT INTO playercreateinfo SELECT 62,class,map,zone,position_x,position_y,position_z,orientation FROM playercreateinfo WHERE race=1;
INSERT INTO playercreateinfo_item SELECT 62,class,itemid,amount,Note FROM playercreateinfo_item WHERE race=1;
INSERT INTO playercreateinfo_action SELECT 62,class,button,action,type FROM playercreateinfo_action WHERE race=1;
INSERT INTO player_race_stats SELECT 62,Strength,Agility,Stamina,Intellect,Spirit FROM player_race_stats WHERE Race=11;
INSERT INTO ascension_custom_class_race SELECT DISTINCT class,62 FROM ascension_custom_class_race;
INSERT INTO playercreateinfo SELECT 63,class,map,zone,position_x,position_y,position_z,orientation FROM playercreateinfo WHERE race=2;
INSERT INTO playercreateinfo_item SELECT 63,class,itemid,amount,Note FROM playercreateinfo_item WHERE race=2;
INSERT INTO playercreateinfo_action SELECT 63,class,button,action,type FROM playercreateinfo_action WHERE race=2;
INSERT INTO player_race_stats SELECT 63,Strength,Agility,Stamina,Intellect,Spirit FROM player_race_stats WHERE Race=10;
INSERT INTO ascension_custom_class_race SELECT DISTINCT class,63 FROM ascension_custom_class_race;
DELETE FROM creature_model_info WHERE DisplayID=977437;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977437,BoundingRadius,CombatReach,0,0 FROM creature_model_info WHERE DisplayID IN (977437,49) ORDER BY DisplayID=977437 DESC LIMIT 1;
DELETE FROM creature_model_info WHERE DisplayID=977438;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977438,BoundingRadius,CombatReach,1,0 FROM creature_model_info WHERE DisplayID IN (977438,50) ORDER BY DisplayID=977438 DESC LIMIT 1;
DELETE FROM creature_model_info WHERE DisplayID=977439;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977439,BoundingRadius,CombatReach,0,0 FROM creature_model_info WHERE DisplayID IN (16125,49) ORDER BY DisplayID=16125 DESC LIMIT 1;
DELETE FROM creature_model_info WHERE DisplayID=977440;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977440,BoundingRadius,CombatReach,1,0 FROM creature_model_info WHERE DisplayID IN (16126,50) ORDER BY DisplayID=16126 DESC LIMIT 1;
DELETE FROM creature_model_info WHERE DisplayID=977441;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977441,BoundingRadius,CombatReach,0,0 FROM creature_model_info WHERE DisplayID IN (16125,49) ORDER BY DisplayID=16125 DESC LIMIT 1;
DELETE FROM creature_model_info WHERE DisplayID=977442;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977442,BoundingRadius,CombatReach,1,0 FROM creature_model_info WHERE DisplayID IN (16126,50) ORDER BY DisplayID=16126 DESC LIMIT 1;
DELETE FROM creature_model_info WHERE DisplayID=977443;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977443,BoundingRadius,CombatReach,0,0 FROM creature_model_info WHERE DisplayID IN (15476,49) ORDER BY DisplayID=15476 DESC LIMIT 1;
DELETE FROM creature_model_info WHERE DisplayID=977444;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977444,BoundingRadius,CombatReach,1,0 FROM creature_model_info WHERE DisplayID IN (15475,50) ORDER BY DisplayID=15475 DESC LIMIT 1;
DELETE FROM creature_model_info WHERE DisplayID=977445;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977445,BoundingRadius,CombatReach,0,0 FROM creature_model_info WHERE DisplayID IN (15476,49) ORDER BY DisplayID=15476 DESC LIMIT 1;
DELETE FROM creature_model_info WHERE DisplayID=977446;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977446,BoundingRadius,CombatReach,1,0 FROM creature_model_info WHERE DisplayID IN (15475,50) ORDER BY DisplayID=15475 DESC LIMIT 1;
DELETE FROM creature_model_info WHERE DisplayID=977447;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977447,BoundingRadius,CombatReach,0,0 FROM creature_model_info WHERE DisplayID IN (55,49) ORDER BY DisplayID=55 DESC LIMIT 1;
DELETE FROM creature_model_info WHERE DisplayID=977448;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977448,BoundingRadius,CombatReach,1,0 FROM creature_model_info WHERE DisplayID IN (56,50) ORDER BY DisplayID=56 DESC LIMIT 1;
DELETE FROM creature_model_info WHERE DisplayID=977449;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977449,BoundingRadius,CombatReach,0,0 FROM creature_model_info WHERE DisplayID IN (15476,49) ORDER BY DisplayID=15476 DESC LIMIT 1;
DELETE FROM creature_model_info WHERE DisplayID=977450;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977450,BoundingRadius,CombatReach,1,0 FROM creature_model_info WHERE DisplayID IN (15475,50) ORDER BY DisplayID=15475 DESC LIMIT 1;
DELETE FROM creature_model_info WHERE DisplayID=977451;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977451,BoundingRadius,CombatReach,0,0 FROM creature_model_info WHERE DisplayID IN (16125,49) ORDER BY DisplayID=16125 DESC LIMIT 1;
DELETE FROM creature_model_info WHERE DisplayID=977452;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977452,BoundingRadius,CombatReach,1,0 FROM creature_model_info WHERE DisplayID IN (16126,50) ORDER BY DisplayID=16126 DESC LIMIT 1;
DELETE FROM creature_model_info WHERE DisplayID=977453;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977453,BoundingRadius,CombatReach,0,0 FROM creature_model_info WHERE DisplayID IN (55,49) ORDER BY DisplayID=55 DESC LIMIT 1;
DELETE FROM creature_model_info WHERE DisplayID=977454;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977454,BoundingRadius,CombatReach,1,0 FROM creature_model_info WHERE DisplayID IN (56,50) ORDER BY DisplayID=56 DESC LIMIT 1;
DELETE FROM creature_model_info WHERE DisplayID=977455;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977455,BoundingRadius,CombatReach,0,0 FROM creature_model_info WHERE DisplayID=977376;
DELETE FROM creature_model_info WHERE DisplayID=977456;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977456,BoundingRadius,CombatReach,1,0 FROM creature_model_info WHERE DisplayID=977377;
DELETE FROM playercreateinfo WHERE race IN (47,57,32,48,49,53,51,56,65,50,72,77,67,66,68,69,70,71,74);
DELETE FROM playercreateinfo_item WHERE race IN (47,57,32,48,49,53,51,56,65,50,72,77,67,66,68,69,70,71,74);
DELETE FROM playercreateinfo_action WHERE race IN (47,57,32,48,49,53,51,56,65,50,72,77,67,66,68,69,70,71,74);
DELETE FROM player_race_stats WHERE Race IN (47,57,32,48,49,53,51,56,65,50,72,77,67,66,68,69,70,71,74);
DELETE FROM ascension_custom_class_race WHERE race IN (47,57,32,48,49,53,51,56,65,50,72,77,67,66,68,69,70,71,74);
INSERT INTO playercreateinfo SELECT 47,class,map,zone,position_x,position_y,position_z,orientation FROM playercreateinfo WHERE race=1;
INSERT INTO playercreateinfo_item SELECT 47,class,itemid,amount,Note FROM playercreateinfo_item WHERE race=1;
INSERT INTO playercreateinfo_action SELECT 47,class,button,action,type FROM playercreateinfo_action WHERE race=1;
INSERT INTO player_race_stats SELECT 47,Strength,Agility,Stamina,Intellect,Spirit FROM player_race_stats WHERE Race=13;
INSERT INTO ascension_custom_class_race SELECT DISTINCT class,47 FROM ascension_custom_class_race;
DELETE FROM creature_model_info WHERE DisplayID=977457;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977457,BoundingRadius,CombatReach,0,0 FROM creature_model_info WHERE DisplayID=49;
DELETE FROM creature_model_info WHERE DisplayID=977458;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977458,BoundingRadius,CombatReach,1,0 FROM creature_model_info WHERE DisplayID=50;
INSERT INTO playercreateinfo SELECT 57,class,map,zone,position_x,position_y,position_z,orientation FROM playercreateinfo WHERE race=2;
INSERT INTO playercreateinfo_item SELECT 57,class,itemid,amount,Note FROM playercreateinfo_item WHERE race=2;
INSERT INTO playercreateinfo_action SELECT 57,class,button,action,type FROM playercreateinfo_action WHERE race=2;
INSERT INTO player_race_stats SELECT 57,Strength,Agility,Stamina,Intellect,Spirit FROM player_race_stats WHERE Race=9;
INSERT INTO ascension_custom_class_race SELECT DISTINCT class,57 FROM ascension_custom_class_race;
DELETE FROM creature_model_info WHERE DisplayID=977459;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977459,BoundingRadius,CombatReach,0,0 FROM creature_model_info WHERE DisplayID=977364;
DELETE FROM creature_model_info WHERE DisplayID=977460;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977460,BoundingRadius,CombatReach,1,0 FROM creature_model_info WHERE DisplayID=977365;
INSERT INTO playercreateinfo SELECT 32,class,map,zone,position_x,position_y,position_z,orientation FROM playercreateinfo WHERE race=1;
INSERT INTO playercreateinfo_item SELECT 32,class,itemid,amount,Note FROM playercreateinfo_item WHERE race=1;
INSERT INTO playercreateinfo_action SELECT 32,class,button,action,type FROM playercreateinfo_action WHERE race=1;
INSERT INTO player_race_stats SELECT 32,Strength,Agility,Stamina,Intellect,Spirit FROM player_race_stats WHERE Race=1;
INSERT INTO ascension_custom_class_race SELECT DISTINCT class,32 FROM ascension_custom_class_race;
DELETE FROM creature_model_info WHERE DisplayID=977461;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977461,BoundingRadius,CombatReach,0,0 FROM creature_model_info WHERE DisplayID=49;
DELETE FROM creature_model_info WHERE DisplayID=977462;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977462,BoundingRadius,CombatReach,1,0 FROM creature_model_info WHERE DisplayID=50;
INSERT INTO playercreateinfo SELECT 48,class,map,zone,position_x,position_y,position_z,orientation FROM playercreateinfo WHERE race=1;
INSERT INTO playercreateinfo_item SELECT 48,class,itemid,amount,Note FROM playercreateinfo_item WHERE race=1;
INSERT INTO playercreateinfo_action SELECT 48,class,button,action,type FROM playercreateinfo_action WHERE race=1;
INSERT INTO player_race_stats SELECT 48,Strength,Agility,Stamina,Intellect,Spirit FROM player_race_stats WHERE Race=3;
INSERT INTO ascension_custom_class_race SELECT DISTINCT class,48 FROM ascension_custom_class_race;
DELETE FROM creature_model_info WHERE DisplayID=977463;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977463,BoundingRadius,CombatReach,0,0 FROM creature_model_info WHERE DisplayID=53;
DELETE FROM creature_model_info WHERE DisplayID=977464;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977464,BoundingRadius,CombatReach,1,0 FROM creature_model_info WHERE DisplayID=54;
INSERT INTO playercreateinfo SELECT 49,class,map,zone,position_x,position_y,position_z,orientation FROM playercreateinfo WHERE race=2;
INSERT INTO playercreateinfo_item SELECT 49,class,itemid,amount,Note FROM playercreateinfo_item WHERE race=2;
INSERT INTO playercreateinfo_action SELECT 49,class,button,action,type FROM playercreateinfo_action WHERE race=2;
INSERT INTO player_race_stats SELECT 49,Strength,Agility,Stamina,Intellect,Spirit FROM player_race_stats WHERE Race=2;
INSERT INTO ascension_custom_class_race SELECT DISTINCT class,49 FROM ascension_custom_class_race;
DELETE FROM creature_model_info WHERE DisplayID=977465;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977465,BoundingRadius,CombatReach,0,0 FROM creature_model_info WHERE DisplayID=51;
DELETE FROM creature_model_info WHERE DisplayID=977466;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977466,BoundingRadius,CombatReach,1,0 FROM creature_model_info WHERE DisplayID=52;
INSERT INTO playercreateinfo SELECT 53,class,map,zone,position_x,position_y,position_z,orientation FROM playercreateinfo WHERE race=2;
INSERT INTO playercreateinfo_item SELECT 53,class,itemid,amount,Note FROM playercreateinfo_item WHERE race=2;
INSERT INTO playercreateinfo_action SELECT 53,class,button,action,type FROM playercreateinfo_action WHERE race=2;
INSERT INTO player_race_stats SELECT 53,Strength,Agility,Stamina,Intellect,Spirit FROM player_race_stats WHERE Race=2;
INSERT INTO ascension_custom_class_race SELECT DISTINCT class,53 FROM ascension_custom_class_race;
DELETE FROM creature_model_info WHERE DisplayID=977467;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977467,BoundingRadius,CombatReach,0,0 FROM creature_model_info WHERE DisplayID=51;
DELETE FROM creature_model_info WHERE DisplayID=977468;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977468,BoundingRadius,CombatReach,1,0 FROM creature_model_info WHERE DisplayID=52;
INSERT INTO playercreateinfo SELECT 51,class,map,zone,position_x,position_y,position_z,orientation FROM playercreateinfo WHERE race=2;
INSERT INTO playercreateinfo_item SELECT 51,class,itemid,amount,Note FROM playercreateinfo_item WHERE race=2;
INSERT INTO playercreateinfo_action SELECT 51,class,button,action,type FROM playercreateinfo_action WHERE race=2;
INSERT INTO player_race_stats SELECT 51,Strength,Agility,Stamina,Intellect,Spirit FROM player_race_stats WHERE Race=5;
INSERT INTO ascension_custom_class_race SELECT DISTINCT class,51 FROM ascension_custom_class_race;
DELETE FROM creature_model_info WHERE DisplayID=977469;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977469,BoundingRadius,CombatReach,0,0 FROM creature_model_info WHERE DisplayID=1563;
DELETE FROM creature_model_info WHERE DisplayID=977470;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977470,BoundingRadius,CombatReach,1,0 FROM creature_model_info WHERE DisplayID=1564;
INSERT INTO playercreateinfo SELECT 56,class,map,zone,position_x,position_y,position_z,orientation FROM playercreateinfo WHERE race=2;
INSERT INTO playercreateinfo_item SELECT 56,class,itemid,amount,Note FROM playercreateinfo_item WHERE race=2;
INSERT INTO playercreateinfo_action SELECT 56,class,button,action,type FROM playercreateinfo_action WHERE race=2;
INSERT INTO player_race_stats SELECT 56,Strength,Agility,Stamina,Intellect,Spirit FROM player_race_stats WHERE Race=4;
INSERT INTO ascension_custom_class_race SELECT DISTINCT class,56 FROM ascension_custom_class_race;
DELETE FROM creature_model_info WHERE DisplayID=977471;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977471,BoundingRadius,CombatReach,0,0 FROM creature_model_info WHERE DisplayID=15476;
DELETE FROM creature_model_info WHERE DisplayID=977472;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977472,BoundingRadius,CombatReach,1,0 FROM creature_model_info WHERE DisplayID=15475;
INSERT INTO playercreateinfo SELECT 65,class,map,zone,position_x,position_y,position_z,orientation FROM playercreateinfo WHERE race=1;
INSERT INTO playercreateinfo_item SELECT 65,class,itemid,amount,Note FROM playercreateinfo_item WHERE race=1;
INSERT INTO playercreateinfo_action SELECT 65,class,button,action,type FROM playercreateinfo_action WHERE race=1;
INSERT INTO player_race_stats SELECT 65,Strength,Agility,Stamina,Intellect,Spirit FROM player_race_stats WHERE Race=1;
INSERT INTO ascension_custom_class_race SELECT DISTINCT class,65 FROM ascension_custom_class_race;
DELETE FROM creature_model_info WHERE DisplayID=977473;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977473,BoundingRadius,CombatReach,0,0 FROM creature_model_info WHERE DisplayID=49;
DELETE FROM creature_model_info WHERE DisplayID=977474;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977474,BoundingRadius,CombatReach,1,0 FROM creature_model_info WHERE DisplayID=50;
INSERT INTO playercreateinfo SELECT 50,class,map,zone,position_x,position_y,position_z,orientation FROM playercreateinfo WHERE race=1;
INSERT INTO playercreateinfo_item SELECT 50,class,itemid,amount,Note FROM playercreateinfo_item WHERE race=1;
INSERT INTO playercreateinfo_action SELECT 50,class,button,action,type FROM playercreateinfo_action WHERE race=1;
INSERT INTO player_race_stats SELECT 50,Strength,Agility,Stamina,Intellect,Spirit FROM player_race_stats WHERE Race=6;
INSERT INTO ascension_custom_class_race SELECT DISTINCT class,50 FROM ascension_custom_class_race;
DELETE FROM creature_model_info WHERE DisplayID=977475;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977475,BoundingRadius,CombatReach,0,0 FROM creature_model_info WHERE DisplayID=59;
DELETE FROM creature_model_info WHERE DisplayID=977476;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977476,BoundingRadius,CombatReach,1,0 FROM creature_model_info WHERE DisplayID=60;
INSERT INTO playercreateinfo SELECT 72,class,map,zone,position_x,position_y,position_z,orientation FROM playercreateinfo WHERE race=2;
INSERT INTO playercreateinfo_item SELECT 72,class,itemid,amount,Note FROM playercreateinfo_item WHERE race=2;
INSERT INTO playercreateinfo_action SELECT 72,class,button,action,type FROM playercreateinfo_action WHERE race=2;
INSERT INTO player_race_stats SELECT 72,Strength,Agility,Stamina,Intellect,Spirit FROM player_race_stats WHERE Race=10;
INSERT INTO ascension_custom_class_race SELECT DISTINCT class,72 FROM ascension_custom_class_race;
DELETE FROM creature_model_info WHERE DisplayID=977477;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977477,BoundingRadius,CombatReach,0,0 FROM creature_model_info WHERE DisplayID=15476;
DELETE FROM creature_model_info WHERE DisplayID=977478;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977478,BoundingRadius,CombatReach,1,0 FROM creature_model_info WHERE DisplayID=15475;
INSERT INTO playercreateinfo SELECT 77,class,map,zone,position_x,position_y,position_z,orientation FROM playercreateinfo WHERE race=1;
INSERT INTO playercreateinfo_item SELECT 77,class,itemid,amount,Note FROM playercreateinfo_item WHERE race=1;
INSERT INTO playercreateinfo_action SELECT 77,class,button,action,type FROM playercreateinfo_action WHERE race=1;
INSERT INTO player_race_stats SELECT 77,Strength,Agility,Stamina,Intellect,Spirit FROM player_race_stats WHERE Race=10;
INSERT INTO ascension_custom_class_race SELECT DISTINCT class,77 FROM ascension_custom_class_race;
DELETE FROM creature_model_info WHERE DisplayID=977479;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977479,BoundingRadius,CombatReach,0,0 FROM creature_model_info WHERE DisplayID=15476;
DELETE FROM creature_model_info WHERE DisplayID=977480;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977480,BoundingRadius,CombatReach,1,0 FROM creature_model_info WHERE DisplayID=15475;
INSERT INTO playercreateinfo SELECT 67,class,map,zone,position_x,position_y,position_z,orientation FROM playercreateinfo WHERE race=1;
INSERT INTO playercreateinfo_item SELECT 67,class,itemid,amount,Note FROM playercreateinfo_item WHERE race=1;
INSERT INTO playercreateinfo_action SELECT 67,class,button,action,type FROM playercreateinfo_action WHERE race=1;
INSERT INTO player_race_stats SELECT 67,Strength,Agility,Stamina,Intellect,Spirit FROM player_race_stats WHERE Race=7;
INSERT INTO ascension_custom_class_race SELECT DISTINCT class,67 FROM ascension_custom_class_race;
DELETE FROM creature_model_info WHERE DisplayID=977481;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977481,BoundingRadius,CombatReach,0,0 FROM creature_model_info WHERE DisplayID=1563;
DELETE FROM creature_model_info WHERE DisplayID=977482;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977482,BoundingRadius,CombatReach,1,0 FROM creature_model_info WHERE DisplayID=1564;
INSERT INTO playercreateinfo SELECT 66,class,map,zone,position_x,position_y,position_z,orientation FROM playercreateinfo WHERE race=2;
INSERT INTO playercreateinfo_item SELECT 66,class,itemid,amount,Note FROM playercreateinfo_item WHERE race=2;
INSERT INTO playercreateinfo_action SELECT 66,class,button,action,type FROM playercreateinfo_action WHERE race=2;
INSERT INTO player_race_stats SELECT 66,Strength,Agility,Stamina,Intellect,Spirit FROM player_race_stats WHERE Race=6;
INSERT INTO ascension_custom_class_race SELECT DISTINCT class,66 FROM ascension_custom_class_race;
DELETE FROM creature_model_info WHERE DisplayID=977483;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977483,BoundingRadius,CombatReach,0,0 FROM creature_model_info WHERE DisplayID=59;
DELETE FROM creature_model_info WHERE DisplayID=977484;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977484,BoundingRadius,CombatReach,1,0 FROM creature_model_info WHERE DisplayID=60;
INSERT INTO playercreateinfo SELECT 68,class,map,zone,position_x,position_y,position_z,orientation FROM playercreateinfo WHERE race=1;
INSERT INTO playercreateinfo_item SELECT 68,class,itemid,amount,Note FROM playercreateinfo_item WHERE race=1;
INSERT INTO playercreateinfo_action SELECT 68,class,button,action,type FROM playercreateinfo_action WHERE race=1;
INSERT INTO player_race_stats SELECT 68,Strength,Agility,Stamina,Intellect,Spirit FROM player_race_stats WHERE Race=3;
INSERT INTO ascension_custom_class_race SELECT DISTINCT class,68 FROM ascension_custom_class_race;
DELETE FROM creature_model_info WHERE DisplayID=977485;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977485,BoundingRadius,CombatReach,0,0 FROM creature_model_info WHERE DisplayID=53;
DELETE FROM creature_model_info WHERE DisplayID=977486;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977486,BoundingRadius,CombatReach,1,0 FROM creature_model_info WHERE DisplayID=54;
INSERT INTO playercreateinfo SELECT 69,class,map,zone,position_x,position_y,position_z,orientation FROM playercreateinfo WHERE race=2;
INSERT INTO playercreateinfo_item SELECT 69,class,itemid,amount,Note FROM playercreateinfo_item WHERE race=2;
INSERT INTO playercreateinfo_action SELECT 69,class,button,action,type FROM playercreateinfo_action WHERE race=2;
INSERT INTO player_race_stats SELECT 69,Strength,Agility,Stamina,Intellect,Spirit FROM player_race_stats WHERE Race=3;
INSERT INTO ascension_custom_class_race SELECT DISTINCT class,69 FROM ascension_custom_class_race;
DELETE FROM creature_model_info WHERE DisplayID=977487;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977487,BoundingRadius,CombatReach,0,0 FROM creature_model_info WHERE DisplayID=53;
DELETE FROM creature_model_info WHERE DisplayID=977488;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977488,BoundingRadius,CombatReach,1,0 FROM creature_model_info WHERE DisplayID=54;
INSERT INTO playercreateinfo SELECT 70,class,map,zone,position_x,position_y,position_z,orientation FROM playercreateinfo WHERE race=2;
INSERT INTO playercreateinfo_item SELECT 70,class,itemid,amount,Note FROM playercreateinfo_item WHERE race=2;
INSERT INTO playercreateinfo_action SELECT 70,class,button,action,type FROM playercreateinfo_action WHERE race=2;
INSERT INTO player_race_stats SELECT 70,Strength,Agility,Stamina,Intellect,Spirit FROM player_race_stats WHERE Race=4;
INSERT INTO ascension_custom_class_race SELECT DISTINCT class,70 FROM ascension_custom_class_race;
DELETE FROM creature_model_info WHERE DisplayID=977489;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977489,BoundingRadius,CombatReach,0,0 FROM creature_model_info WHERE DisplayID=55;
DELETE FROM creature_model_info WHERE DisplayID=977490;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977490,BoundingRadius,CombatReach,1,0 FROM creature_model_info WHERE DisplayID=56;
INSERT INTO playercreateinfo SELECT 71,class,map,zone,position_x,position_y,position_z,orientation FROM playercreateinfo WHERE race=1;
INSERT INTO playercreateinfo_item SELECT 71,class,itemid,amount,Note FROM playercreateinfo_item WHERE race=1;
INSERT INTO playercreateinfo_action SELECT 71,class,button,action,type FROM playercreateinfo_action WHERE race=1;
INSERT INTO player_race_stats SELECT 71,Strength,Agility,Stamina,Intellect,Spirit FROM player_race_stats WHERE Race=4;
INSERT INTO ascension_custom_class_race SELECT DISTINCT class,71 FROM ascension_custom_class_race;
DELETE FROM creature_model_info WHERE DisplayID=977491;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977491,BoundingRadius,CombatReach,0,0 FROM creature_model_info WHERE DisplayID=55;
DELETE FROM creature_model_info WHERE DisplayID=977492;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977492,BoundingRadius,CombatReach,1,0 FROM creature_model_info WHERE DisplayID=56;
INSERT INTO playercreateinfo SELECT 74,class,map,zone,position_x,position_y,position_z,orientation FROM playercreateinfo WHERE race=2;
INSERT INTO playercreateinfo_item SELECT 74,class,itemid,amount,Note FROM playercreateinfo_item WHERE race=2;
INSERT INTO playercreateinfo_action SELECT 74,class,button,action,type FROM playercreateinfo_action WHERE race=2;
INSERT INTO player_race_stats SELECT 74,Strength,Agility,Stamina,Intellect,Spirit FROM player_race_stats WHERE Race=19;
INSERT INTO ascension_custom_class_race SELECT DISTINCT class,74 FROM ascension_custom_class_race;
DELETE FROM creature_model_info WHERE DisplayID=977493;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977493,BoundingRadius,CombatReach,0,0 FROM creature_model_info WHERE DisplayID=141254;
DELETE FROM creature_model_info WHERE DisplayID=977494;
INSERT INTO creature_model_info (DisplayID,BoundingRadius,CombatReach,Gender,DisplayID_Other_Gender) SELECT 977494,BoundingRadius,CombatReach,1,0 FROM creature_model_info WHERE DisplayID=141255;
COMMIT;
